### ISSUE TITLE
Consulting for BPMF

### ISSUE THREAD

**Issue by GPeng00** [ebeauce/Seismic_BPMF#34]
Hi Eric, Can BPMF detect and locate low-frequency earthquake or tremor?

**Comment by ebeauce** [comment]
Hi @GPeng00 ,

A similar workflow -- backprojection + template matching -- has already been used to detect and locate LFEs in Mexico (see papers by William B. Frank 2013 and 2014). So, yes, BPMF can be used for LFEs. What you detect with backprojection will highly depends on the characteristic function of the seismograms you backproject (that is, envelope, kurtosis, STA/LTA, etc...). In [Using systematically characterized low‐frequency earthquakes as a fault probe in Guerrero, Mexico](https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1002/2014JB011457), the authors backproject the squared seismograms.

As for tremors, you can use backprojection on the inter-station envelope cross-correlations to detect and locate them. I am not aware of any work that has made a tremor catalog with template matching. At least, not with waveforms (there might have been template matching of amplitude spectra).
