### ISSUE TITLE
Instalation error

### ISSUE THREAD

**Issue by ladominguez** [ebeauce/Seismic_BPMF#66]
Thank you for putting together this code. I am trying to install it both on a Mac computer and a Linux computer. But in both cases, I get the following error. I'm following the instructions on the documentation.

ERROR: Could not find a version that satisfies the requirement beampower (from bpmf) (from versions: none)
ERROR: No matching distribution found for beampower

**Comment by ebeauce** [comment]
Hello Luis,

Can you give me more info on how you are trying to install bpmf? You need
to install "beampower" and "fast_matched_filter" first, which require
compilation and therefore cannot be easily installed with pip or conda. I
suggest you follow the instructions at the beginning of the tutorial at
https://ebeauce.github.io/Seismic_BPMF/tutorial/general.html

Following this procedure should work. Let me know how it goes.

Best,
Eric

**Comment by ladominguez** [comment]
Thank you so much for your support. I apologize for not reading the tutorial first. I was able to install BPMF.

**Comment by ebeauce** [comment]
No worries, I'm glad it solved your problem.

Eric
